[phases.setup]
nixPkgs = ["python3.12", "gcc"]

[phases.install]
cmds = [
  "python3.12 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python bot.py"
