[phases.setup]
nixPkgs = ["...", "python312"]

[phases.install]
cmds = [
  "python3.12 -m venv /opt/venv --clear",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[staticAssets]
skip = true

[start]
cmd = ". /opt/venv/bin/activate && python bot.py"
